version: "3.8"
services:
    db:
        image: postgres:12.4-alpine
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: test_db
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4_container
        restart: always
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: test_email@test_domain.com
            PGADMIN_DEFAULT_PASSWORD: test_password
        volumes:
            - pgadmin-data:/var/lib/pgadmin
volumes:
    db:
        driver: local
    pgadmin-data:
